### ISSUE TITLE
[Windows] Only working with global path ?

### ISSUE THREAD

**Issue by Khopa** [proboston/sails-fixtures#6]
I'm developing on Windows 7, using sails 0.11.0 and sails-fixtures 0.1.5

When i'm using a relative path to locate my fixtures like this :

    var fixtures = require('sails-fixtures');
    
    module.exports.bootstrap = function(cb) {
    
      fixtures.init({
        'dir':'./fixtures/dev'
      }, cb);

    };

The following error is triggered :

    Error: Cannot find module './fixtures/dev/users.fixture.json'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at C:\Users\me\project\server\node_modules\sails-fixtures\lib\index.js:33:19

So i looked at the sources, and the error seems to be triggered when the fixtures files are loaded through *require*, though the glob module manage to resolve them.

This is the line that triggers the error :

    parallel.push(require(files[ifp]));

I managed to resolve the issue by using a global path, so that require is able to resolve the files.

    var fixtures = require('sails-fixtures');
    
    module.exports.bootstrap = function(cb) {
    
     fixtures.init({
        'dir':process.cwd() + 'fixtures/dev'
      }, cb);
    
    };

**Is it an expected behaviour or only a Windows related issue ?**

**Comment by just-paja** [comment]
Hi, thanks for this report. I [changed](https://github.com/proboston/sails-fixtures/commit/5e14fa9d5287aae266b0a134cc2394303760d6a4) the behaviour to use relative paths. However I currently don't have access Windows OS to test this. Could you please try master version?

**Comment by Khopa** [comment]
I tried with the master version and this is now working with both relative and/or global paths on Windows.

Thanks for the fix !
